<?php

namespace ContainerSvInU6P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EhcbglAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ehcbglA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ehcbglA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'anagram' => ['services', 'App\\Controller\\Anagram', 'getAnagramService', true],
        ], [
            'anagram' => 'App\\Controller\\Anagram',
        ]);
    }
}
