<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxTunvz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxTunvz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxTunvz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxTunvz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxTunvz\App_KernelDevDebugContainer([
    'container.build_hash' => 'IxTunvz',
    'container.build_id' => 'c3424768',
    'container.build_time' => 1654256667,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxTunvz');
